name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bot:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, macos-15, macos-26 ]
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    uses: ./.github/workflows/brew-check.yml
    with:
      os: ${{ matrix.os }}
